# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: write

env:
  REACT_APP_INFURA_KEY: 'REACT_APP_INFURA_KEY'
  REACT_APP_CONTRACT: '0x4ea67aebb61f7ff6e15e237c8b79d29c41f750fd'
  REACT_APP_SUBGRAPHS: 'https://api.thegraph.com/subgraphs/name/vince0656/brand-central'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: 'echo REACT_APP_INFURA_KEY="$REACT_APP_INFURA_KEY" >> .env'
      - run: 'echo REACT_APP_CONTRACT="$REACT_APP_CONTRACT" >> .env'
      - run: 'echo REACT_APP_SUBGRAPHS="$REACT_APP_SUBGRAPHS" >> .env'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          folder: build
